backend:
	name: git-gateway
	branch: main

media_folder: "public/assets/blog"
public_folder: "/assets/blog"

collections:
	- name: "blog"
		label: "Blog"
		folder: "src/blog"
		create: true
		slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
		fields:
			- { name: "title", label: "Title", widget: "string" }
			- { name: "description", label: "Description", widget: "string" }
			- { name: "author", label: "Author", widget: "string" }
			- { name: "date", label: "Date", widget: "datetime" }
			- { name: "tags", label: "Tags", widget: "list", default: "['posts']"}
			- { name: "image", label: "Featured Image", widget: "image" }
			- {	name: "imageAlt", label: "Image Caption", widget: "string" }
			- { name: "body", label: "body"}